### PR TITLE
SNO-110 Stop blocking app when wrong metamask network is connected

### PR DESCRIPTION
**Pull request by emzet93**
https://linear.app/snowfork/issue/SNO-110/stop-wallet-connect-flow-blocking-whole-app

For now it's only about case when wrong metamask network is connected. Not sure if we should implement something similar for other cases (like not having metamask/polkadot extensions installed or not connected account).

Changes includes:
- Stop blocking app when wrong metamask network is connected
- Add button for switching to proper network

### CODE REVIEW

**Comment by musnit** [comment]
looks great. one small thing - i notice that when i select an asset while on mainnet, it shows me the mainnet token list. this is fine, but its way longer than the ropsten one so the ui breaks. can you add overflow:scroll to the erc20 seletion ui along with this PR?

**Comment by musnit** [comment]
And yeh, for the other cases with metamask not installed/no connected account, i think overall we should move to a third party library to handle that all for us

**Comment by emzet93** [comment]
> looks great. one small thing - i notice that when i select an asset while on mainnet, it shows me the mainnet token list. this is fine, but its way longer than the ropsten one so the ui breaks. can you add overflow:scroll to the erc20 seletion ui along with this PR?

Sure, I will adjust that. But also when I switched to e.g. Rinkeby the token list is also broken - there are some images missing:
image

I'm wondering if we should handle all that stuff. Maybe it would be better to just disable token selection if there is wrong network connected?

**Comment by musnit** [comment]
yeh - i think: when you click the select asset button, show up the network change flow instead of opening the modal

**Comment by emzet93** [comment]
> yeh - i think: when you click the select asset button, show up the network change flow instead of opening the modal

ok, done. Clicking select asset button will open metamask popup. Also fixed the overflow so it should work fine on miannet

**Review by musnit — APPROVED** [review]

**Pull request merged**
